// Errors
export const ERROR_RESET_MESSAGE = 'ERROR_RESET_MESSAGE'

// Projects
export const PROJECTS_FAILURE = 'PROJECTS_FAILURE'
export const PROJECTS_REQUEST = 'PROJECTS_REQUEST'
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS'
